### ISSUE TITLE
demo code in Readme produce error.

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [nwilming/pyedfread#10]
I am running this :
`events= edf.trials2events(events, messages) ` 
It produces error messages as followed :
` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pohsuanh/miniconda3/envs/alma/lib/python3.6/site-packages/pyedfread/edf.py", line 79, in trials2events
    return events.merge(messages, how='left', on=['trial'])
  File "/home/pohsuanh/miniconda3/envs/alma/lib/python3.6/site-packages/pandas/core/frame.py", line 6379, in merge
    copy=copy, indicator=indicator, validate=validate)
  File "/home/pohsuanh/miniconda3/envs/alma/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 60, in merge
    validate=validate)
  File "/home/pohsuanh/miniconda3/envs/alma/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 550, in __init__
    self.join_names) = self._get_merge_keys()
  File "/home/pohsuanh/miniconda3/envs/alma/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 856, in _get_merge_keys
    rk, stacklevel=stacklevel))
  File "/home/pohsuanh/miniconda3/envs/alma/lib/python3.6/site-packages/pandas/core/generic.py", line 1379, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'trial'
` 

It seems like there is no key named trial by default, and it doens't allow no giving a key. Could you elaborate how can I use edf.trials2events(events, messages) `  with different keys ? Thank you.

**Comment by nwilming** [comment]
trials2events is basically a one liner in pandas: `events.merge(messages, how='left', on=['trial'])`
Maybe try to use this directly and exchange 'trial' for a key that is present in events and messages.
